import { Inter } from "next/font/google";
import "./globals.css";
import AuthGuard from "@/components/AuthGuard";
import InventuraGuard from "@/components/InventuraGuard";

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

export const metadata = {
  title: "EIRA Stocktaking",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link href="https://fonts.googleapis.com/icon?family=Material+Icons+Round" rel="stylesheet" />
      </head>
      <body
        className={`${inter.variable} antialiased`}
      >
        <AuthGuard>
          <InventuraGuard>
            {children}
          </InventuraGuard>
        </AuthGuard>
      </body>
    </html>
  );
}
